version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing npm..."
      - npm install
      - npm install -g aws-cdk@2
  pre_build:
    commands:
      - echo "Running Node.js version..."
      - node --version
      - echo "Running npm version..."
      - npm --version
      - ls 
      - cdk --version
      - cdk bootstrap aws://650251698778/ap-northeast-1
  build:
    commands:
      - echo "Build phase completed."